import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import React from "react";
import { PreloadResources } from "@/app/preload-resources";
import Head from "next/head";

import "@rainbow-me/rainbowkit/styles.css";
import Providers from "./providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Expatsio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add the favicon link here */}
        <link rel="icon" href="https://expatsio.b-cdn.net/e_1.png" />
        {/* <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js"></script> */}
      </head>
      {/* <Head>
        <link rel="shortcut icon" href="https://tuk-cdn.s3.amazonaws.com/can-uploader/favicon_-_.png" type="image/x-icon" />
        <link rel="icon" href="https://tuk-cdn.s3.amazonaws.com/can-uploader/favicon_-_.png" />
      </Head> */}
      <PreloadResources />
      <body className={inter.className}>
        <Providers>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
